inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1

  Exclude:
    - bin/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
